version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.18.0
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=true
      - discovery.type=single-node
      # Menghindari error memori (penting untuk Docker)
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - ELASTIC_PASSWORD=md+tlgNOX2Z=xkGXWjbP
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data # Persistensi data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elastic_net

  kibana:
    image: docker.elastic.co/kibana/kibana:8.18.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=md+tlgNOX2Z=xkGXWjbP
    ports:
      - 5601:5601
    networks:
      - elastic_net
    depends_on:
      - elasticsearch # Kibana akan menunggu Elasticsearch siap

volumes:
  esdata: # Volume untuk menyimpan data Elasticsearch agar tidak hilang saat kontainer dihapus

networks:
  elastic_net: # Network bridge khusus untuk layanan Elastic
    driver: bridge